### ISSUE TITLE
Cho phép khách đặt câu hỏi

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/module-faq#18]
Hiện tại em mới thấy có mục cho phép đặt câu hỏi ngoài site nhưng mà thành viên mới đăng được. mong đội code cho phép khách vẫn đăng được câu hỏi.

**Comment by thehung** [comment]
Chào bạn,

Module FAQ sẽ xóa bỏ tính năng hỏi đáp (QA), để đảm bảo các tính năng đúng như tên gọi của nó.

**Comment by motcaitenit38** [comment]
tức là sao ạ anh?

**Comment by thehung** [comment]
Tức là tính năng đặt câu hỏi sẽ bị loại bỏ khỏi module FAQ bạn nhé!
