### ISSUE TITLE
Góp ý Module faq cho phiên bản Nukeviet 4

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/module-faq#4]
Trước đây mình có dùng module faq cho phiên bản 3.4 đầy đủ các block như:
block: global.faq_news; global.block_faq_top; và module.block_faq_search; global.block_send_question
(Câu hỏi mới; câu hỏi top; tìm kiếm chuyên mục/câu hỏi và block gửi câu hỏi)
Nay nukeviet 4 đã ra mắt, mình mong đội code nghiên cứu để cộng đồng có một module faq đầy đủ các chức năng. Thank!

**Comment by vuthao** [comment]
Thế bạn đóng góp các block này để chúng tôi nâng cấp nhé.

**Comment by hoanglongvnpt** [comment]
Module faq v3.4
http://www.mediafire.com/download/kblxlw2qm1ttrxs/nv3_module_faq.zip

**Comment by thehung** [comment]
FAQ tức là các câu hỏi thường gặp, nó không phải module hỏi đáp. Việc biến thành module hỏi đáp nhiều khi hơi thừa (vì đã có module contact) và cũng hơi thiếu (vì chưa đạt đến đăng cấp của hệ thống support tickits).

**Comment by hoanglongvnpt** [comment]
Module contact chỉ là module liên hệ với ban quản trị, còn hỏi đáp nó còn có các block đi kèm để hiển thị câu hỏi và câu trả lời ra trang chủ

**Comment by thehung** [comment]
Như đã nói: FAQ tức là các câu hỏi thường gặp, nó không phải module hỏi đáp. Việc bạn có bổ sung block như bạn nói nó cũng không thành module hỏi đáp được mà cần bổ sung chức năng cho người sử dụng gửi câu hỏi và tham gia trả lời nữa. Như thế nó trở thành module khác rồi, không còn là module FAQ. Tốt nhất là viết module mới, tránh ôm đồm.
