### ISSUE TITLE
Phát triển module faq

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-faq#6]
1. - Thêm cấu hình cho phép đặt câu hỏi, và trả lời ngoài site. (Yêu cầu là thành viên)
2. - Thêm chức năng duyệt câu hỏi và trả lời. 
-  Có chức năng xóa nếu là bài viết không hợp lệ.
- Nếu bài không hợp lệ, thì xóa đi, và thông báo lại cho thành viên qua email

**Comment by ngocphan123** [comment]
Chức năng duyệt câu hỏi được lưu trong bảng tmp, với 3 trạng thái lưu duyệt và xóa.
Có 2 loại thời gian: thời gian người đăng câu hỏi, thời gian duyệt.
Có 2 loại user: người đăng bài, người duyệt bài
Khi duyệt thì sẽ được chuyển sang bảng quản lý câu hỏi với trạng thái duyệt
      + Bảng quản lý câu hỏi có 3 trạng thái : 0: là không hoạt động, 1:hoạt động, 2: nổi bật=>thiết kế thêm nút bài viết nổi bật trong giao diện duyệt

**Comment by ngocphan123** [comment]
Có bắt buộc phải có câu trả lời không? khi duyệt thì admin buộc phải duyệt câu trả lời?

**Comment by vuthao** [comment]
Hiện tại đã phát triển xong và lưu trữ tại: https://github.com/nukeviet/module-faq/tree/qa

**Comment by ngoctu2008** [comment]
Anh còn bản này không ạ? https://github.com/nukeviet/module-faq/tree/qa
